name: Generate PR Description
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  generate-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate PR Description
        uses: SearchKings/pr-description-generator@fix/test
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
