name: Release
on:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.9.0
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    name: Semantic Release
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Semantic Release
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm ci
          npm run lint
          npm run build
          npm run semantic-release
          # Update build with latest version
          npm run build:prod && git add build/\* && git commit -m "chore: update build" && git push

  merge-release:
    needs: semantic-release
    runs-on: ubuntu-latest
    name: Merge release to develop
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          token: ${{ secrets.ACTIONS_TOKEN }}
          fetch-depth: 0
      - run: |
          git fetch
          git config --global user.email "actions@github.com"
          git config --global user.name "Github"
          git merge origin/master
          git push --force
